---
language: ruby
bundler_args: "--without development"
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.6.0" PARSER="future"
  - PUPPET_VERSION="~> 3.7.0" PARSER="future"
notifications:
  email: false
  hipchat:
    on_success: change
    on_failure: change
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    rooms:
      secure: YV98rDQEAgVMGdzsNWUBy35l2uSLjEDiwbOdYpQhk5LhZ+5UzNYHN9gAhF0Zvwub2MdOWQVjgbVFVdvHFEDvEhbphDLCwWZFEk65/gIaj7O2KdkPCiw9X2Or9qvwhWjL/7UwdZUBF/vy+stlpJ+JrOjNq4AhUI/ZB8sgF8XHQok=
