sudo: false
cache: bundler
language: ruby
before_install: rm Gemfile.lock || true
install:
  - bundle install --without development system_tests
  - bundle exec rake spec_prep
rvm:
- 2.0.0
- 2.1.0
script: bundle exec rake test
env:
- PUPPET_VERSION="~> 3.2.0"
- PUPPET_VERSION="~> 3.3.0"
- PUPPET_VERSION="~> 3.4.0"
- PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
- PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
- PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
- PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
- PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
matrix:
  include:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
  - rvm: 2.2
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
  exclude:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
  allow_failures:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
  - rvm: 2.2
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
notifications:
  email: false
  slack:
    secure: Jn+sIT/zyQeqRRnfUsdg3Pmj8PHZWRk+TlJX91JUXpdXV45jXnOZ48Jrwcov0A9KhYVj3IDvUBh2Lb1R2dglfwtyGL0GKvJBVV8uN3BWLJo238xhnSMvG1aoiVvNnLd4WlcNuOASNKhvQHbn7cxX2xdjS7cxHYkDcOl9fCRX6RA=
