language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
script: bundle exec rake test
env:
- PUPPET_VERSION="~> 2.7.0"
- PUPPET_VERSION="~> 3.1.0"
- PUPPET_VERSION="~> 3.2.0"
- PUPPET_VERSION="~> 3.3.0"
- PUPPET_VERSION="~> 3.4.0"
- PUPPET_VERSION="~> 3.5.0"
- PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
notifications:
  hipchat:
    rooms:
      secure: bL/Oz7NC2peTB/5yMZADV0zQSttbohtikHRrg7XeV6GW3uxJSbrUXVxZiQ/9QrkV8iFKA0DqQXoP5aYY8l99/ASUQsF2YiZDhB1Zgtvrx4FRdvrZTFGk7B5Gshyu6SZNfQ8pkemyrePxaVw+ELBcDRaU0GnomcjkOfzDD637NUk=
